export enum ErrorCode {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  CODE_MISMATCH = 'CODE_MISMATCH',
  TOKEN_MISMATCH = 'TOKEN_MISMATCH',
  EMAIL_CODE_MISMATCH = 'EMAIL_CODE_MISMATCH',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  QUERY_ERROR = 'QUERY_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',

}
